
server:
  port: 8080

spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.102:1521:orcl
    username: system
    password: ADMIN
mybatis:
  mapper-locations: classpath:mapper/*.xml
